fs: fix wrong variable from merge conflict
/mnt/workdir/aarch64-elf-gcc/bin/aarch64-elf-ld: fs/ext4/inode.o: in function `__ext4_block_zero_page_range':
inode.c:(.text+0x39fc): undefined reference to `ext4_encrypted_inode'
/mnt/workdir/aarch64-elf-gcc/bin/aarch64-elf-ld: fs/ext4/inode.o: in function `ext4_truncate':
inode.c:(.text+0x7fc4): undefined reference to `ext4_encrypted_inode'
/mnt/workdir/aarch64-elf-gcc/bin/aarch64-elf-ld: fs/ext4/inode.o: in function `ext4_direct_IO':
inode.c:(.text+0x8fe8): undefined reference to `ext4_encrypted_inode'
/mnt/workdir/aarch64-elf-gcc/bin/aarch64-elf-ld: inode.c:(.text+0x93d4): undefined reference to `ext4_encrypted_inode'
/mnt/workdir/aarch64-elf-gcc/bin/aarch64-elf-ld: fs/f2fs/data.o: in function `f2fs_grab_read_bio':
data.c:(.text+0x3024): undefined reference to `f2fs_encrypted_inode'